# Configuración del servidor y comportamiento general
server:
  error:
    include-message: always

# Configuración de la Base de Datos (PostgreSQL)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecofreshfood_auth_db # Asegúrate de que esta DB exista en tu Postgres
    username: admin
    password: admin12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Crea o actualiza las tablas automáticamente basándose en tus entidades
    show-sql: true # Muestra las consultas SQL en la consola (ideal para desarrollo)
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Registro automático en el Servidor Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # Recomendado en entornos de microservicios para evitar problemas de DNS locales

# Propiedades personalizadas para la seguridad de tu JwtProvider
jwt:
  # La clave debe ser un String largo, complejo y seguro (mínimo 256 bits / 32 caracteres)
  secret: "TuClaveSecretaSuperSeguraYMuyLargaParaFirmarLosTokensJWT1234567890EcoFreshFood2026"
  # Tiempo de expiración del token en milisegundos (Ej: 3600000 ms = 1 hora)
  expiration: 3600000

# Exponer endpoints de monitoreo (Opcional, útil para Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health, info
